#pragma once

#define DIGITS_AMOUNT 6

#define TOP_SEGMENT 0
#define TOP_LEFT_SEGMENT 1
#define TOP_RIGHT_SEGMENT 2
#define MID_SEGMENT 3
#define BOT_LEFT_SEGMENT 4
#define BOT_RIGHT_SEGMENT 5
#define BOT_SEGMENT 6
#define SEGMENTS_AMOUNT 7